Repository kubeedge/dashboard, pull requests merged in 2025-02, with the labels that each got.

#42 Auto-generate footer year dynamically: replaced hardcoded year wit…
  src/app/login/page.tsx
Labels: kind/feature, size/XS, approved, lgtm

#34 Fix dialogs style errors
  src/component/AddClusterRoleBindingDialog/index.tsx
  src/component/AddClusterRoleDialog/index.tsx
  src/component/AddConfigmapDialog/index.tsx
  src/component/AddDeviceDialog/index.tsx
  src/component/AddDeviceModelDialog/index.tsx
  src/component/AddEdgeApplicationDialog/index.tsx
  src/component/AddNodeDialog/index.tsx
  src/component/AddNodeGroupDialog/index.tsx
  src/component/AddRoleBindingDialog/index.tsx
  src/component/AddRoleDialog/index.tsx
  src/component/AddRuleDialog/index.tsx
  src/component/AddRuleEndpointDialog/index.tsx
  src/component/AddSecretDialog/index.tsx
  src/component/AddServiceAccountDialog/index.tsx
  src/component/AddServiceDialog/index.tsx
  src/component/DeploymentDrawer/DeploymentForms/ContainerInfoForm.tsx
  src/component/DeploymentDrawer/DeploymentForms/StorageMountForm.tsx
Labels: kind/bug, approved, size/L, lgtm

#40 Fix broken links in contributing doc.
  CONTRIBUTING.md
Labels: size/XS, approved, kind/documentation, lgtm
