Repository kubeedge/dashboard, pull requests merged in 2025-07, with the labels that each got.

#57 Add proposal directory
  docs/proposals/README.md
Labels: kind/documentation, size/S, lgtm

#62 fix: making full menu item clickable
  modules/web/src/component/SideNav/index.tsx
Labels: kind/bug, approved, size/S, lgtm

#63 Apply to be a reviewer
  OWNERS
Labels: size/XS, approved, kind/documentation, lgtm
